/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Resturent;
import java.awt.Component;
import javax.swing.JTextField;
import java.awt.TextField;
import javax.swing.UIManager;
import javax.swing.LookAndFeel;
import javax.swing.UnsupportedLookAndFeelException;
import java.util.*;
import java.text.*;

/**
 *
 * @author HP
 */
public class Resturent extends javax.swing.JFrame {

    /**
     * Creates new form Resturent
     */
    public Resturent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jtxtChickenBurger = new javax.swing.JTextField();
        jlblTax1 = new javax.swing.JLabel();
        jlblSubTotal1 = new javax.swing.JLabel();
        jlblTotal1 = new javax.swing.JLabel();
        jtxtFiletOFish = new javax.swing.JTextField();
        jtxtBaconAndCheeseBurger = new javax.swing.JTextField();
        jlblTax2 = new javax.swing.JLabel();
        jlblSubTotal2 = new javax.swing.JLabel();
        jtxtChickenLegend = new javax.swing.JTextField();
        jlblTotal2 = new javax.swing.JLabel();
        jtxtChickenBurgerMeal = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtReciept = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jtxtTax = new javax.swing.JTextField();
        jlblTax = new javax.swing.JLabel();
        jlblSubTotal = new javax.swing.JLabel();
        jlblTotal = new javax.swing.JLabel();
        jtxtSubTotal = new javax.swing.JTextField();
        jtxtTotal = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jBtnReset = new javax.swing.JButton();
        jBtnTotal = new javax.swing.JButton();
        jBtnReciept = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jtxtVanilaCone = new javax.swing.JTextField();
        jlblTax3 = new javax.swing.JLabel();
        jlblSubTotal3 = new javax.swing.JLabel();
        jlblTotal3 = new javax.swing.JLabel();
        jtxtMilkShake = new javax.swing.JTextField();
        jtxtChocotaleMilkShake = new javax.swing.JTextField();
        jlblTax4 = new javax.swing.JLabel();
        jlblSubTotal4 = new javax.swing.JLabel();
        jtxtClasicVanila = new javax.swing.JTextField();
        jlblTotal4 = new javax.swing.JLabel();
        jtxtVanilaMilkShake = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jtxtMeals = new javax.swing.JTextField();
        jlblTax5 = new javax.swing.JLabel();
        jlblSubTotal5 = new javax.swing.JLabel();
        jlblTotal5 = new javax.swing.JLabel();
        jtxtDrinks = new javax.swing.JTextField();
        jtxtCostOfItems = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        jLabel2.setText("jLabel2");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 66)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Resturent Management System");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.setAlignmentX(34.0F);

        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\JAVA\\Resturent\\Resturent\\restaurant1.png")); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel2))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel2))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 1430, 150));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jtxtChickenBurger.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtChickenBurger.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtChickenBurger.setText("0");
        jtxtChickenBurger.setToolTipText("");

        jlblTax1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTax1.setText("Meals");

        jlblSubTotal1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblSubTotal1.setText("Filet-O-Fish");

        jlblTotal1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTotal1.setText("Chicken Burger");

        jtxtFiletOFish.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtFiletOFish.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtFiletOFish.setText("0");
        jtxtFiletOFish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFiletOFishActionPerformed(evt);
            }
        });

        jtxtBaconAndCheeseBurger.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtBaconAndCheeseBurger.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtBaconAndCheeseBurger.setText("0");

        jlblTax2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTax2.setText("Chicken Legend");

        jlblSubTotal2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblSubTotal2.setText("Chicken Burger Meal");

        jtxtChickenLegend.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtChickenLegend.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtChickenLegend.setText("0");

        jlblTotal2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTotal2.setText("Bacon and Cheese Burger");

        jtxtChickenBurgerMeal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtChickenBurgerMeal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtChickenBurgerMeal.setText("0");
        jtxtChickenBurgerMeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtChickenBurgerMealActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlblTax1)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jlblTotal2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jlblTax2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlblSubTotal2))
                        .addComponent(jlblSubTotal1)
                        .addComponent(jlblTotal1)))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtxtChickenBurgerMeal)
                    .addComponent(jtxtChickenLegend)
                    .addComponent(jtxtChickenBurger)
                    .addComponent(jtxtBaconAndCheeseBurger)
                    .addComponent(jtxtFiletOFish, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
                .addGap(51, 51, 51))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jlblTax1)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblSubTotal1)
                    .addComponent(jtxtFiletOFish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblTotal1)
                    .addComponent(jtxtChickenBurger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblTax2)
                    .addComponent(jtxtChickenLegend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jlblSubTotal2)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblTotal2)
                            .addComponent(jtxtBaconAndCheeseBurger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jtxtChickenBurgerMeal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 490, 310));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jtxtReciept.setColumns(20);
        jtxtReciept.setRows(5);
        jScrollPane1.setViewportView(jtxtReciept);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 200, 400, 570));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jtxtTax.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jlblTax.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTax.setText("Tax");

        jlblSubTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblSubTotal.setText("Sub Total");

        jlblTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTotal.setText("Total");

        jtxtSubTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jtxtTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jlblTax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlblSubTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jlblTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtTax, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(jtxtSubTotal)
                    .addComponent(jtxtTotal))
                .addGap(50, 50, 50))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jtxtTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblTax)
                .addGap(18, 18, 18)
                .addComponent(jlblSubTotal)
                .addGap(18, 18, 18)
                .addComponent(jlblTotal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 530, 490, 140));

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jBtnReset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnReset.setText("Reset");
        jBtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnResetActionPerformed(evt);
            }
        });

        jBtnTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnTotal.setText("Total");
        jBtnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTotalActionPerformed(evt);
            }
        });

        jBtnReciept.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnReciept.setText("Reciept");
        jBtnReciept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRecieptActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jBtnTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157)
                .addComponent(jBtnReciept)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                .addComponent(jBtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(158, 158, 158)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnTotal)
                    .addComponent(jBtnReciept)
                    .addComponent(jButton4)
                    .addComponent(jBtnReset))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 690, 1000, 80));

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jtxtVanilaCone.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtVanilaCone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtVanilaCone.setText("0");

        jlblTax3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTax3.setText("Drinks");

        jlblSubTotal3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblSubTotal3.setText("Milk Shake");

        jlblTotal3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTotal3.setText("Valina Cone");

        jtxtMilkShake.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtMilkShake.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtMilkShake.setText("0");
        jtxtMilkShake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtMilkShakeActionPerformed(evt);
            }
        });

        jtxtChocotaleMilkShake.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtChocotaleMilkShake.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtChocotaleMilkShake.setText("0");

        jlblTax4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTax4.setText("Clasic Vanila");

        jlblSubTotal4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblSubTotal4.setText("Valina Milk Shake");

        jtxtClasicVanila.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtClasicVanila.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtClasicVanila.setText("0");

        jlblTotal4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTotal4.setText("Chocolate Milk Shake ");

        jtxtVanilaMilkShake.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtVanilaMilkShake.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtVanilaMilkShake.setText("0");
        jtxtVanilaMilkShake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtVanilaMilkShakeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlblTax3)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jlblTotal4)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jlblTax4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlblSubTotal4))
                        .addComponent(jlblSubTotal3)
                        .addComponent(jlblTotal3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtVanilaMilkShake, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtxtClasicVanila, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtxtVanilaCone, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtxtMilkShake, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(jtxtChocotaleMilkShake))
                .addGap(51, 51, 51))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jlblTax3)
                .addGap(26, 26, 26)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblSubTotal3)
                    .addComponent(jtxtMilkShake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblTotal3)
                    .addComponent(jtxtVanilaCone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblTax4)
                    .addComponent(jtxtClasicVanila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jlblSubTotal4)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblTotal4)
                            .addComponent(jtxtChocotaleMilkShake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jtxtVanilaMilkShake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, 490, -1));

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jtxtMeals.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jlblTax5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTax5.setText("Cost of Meals");

        jlblSubTotal5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblSubTotal5.setText("Cost of Drinks ");

        jlblTotal5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTotal5.setText("Cost of Made");

        jtxtDrinks.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jtxtCostOfItems.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jlblTax5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlblSubTotal5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jlblTotal5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtMeals, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(jtxtDrinks)
                    .addComponent(jtxtCostOfItems))
                .addGap(52, 52, 52))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jtxtMeals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtxtDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtxtCostOfItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblTax5)
                .addGap(18, 18, 18)
                .addComponent(jlblSubTotal5)
                .addGap(18, 18, 18)
                .addComponent(jlblTotal5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 490, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnRecieptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRecieptActionPerformed
        int refs = 1325 + (int)(Math.random()*4238);
        
        Calendar timer = Calendar.getInstance();
        timer.getTime();
        SimpleDateFormat tTime = new SimpleDateFormat("HH:mm:ss");
        tTime.format(timer.getTime());
        SimpleDateFormat tDate = new SimpleDateFormat("dd:MM:yyyy");
        tDate.format(timer.getTime());
                
                jtxtReciept.append("\tRestutent Management System:\n"+
                        "Reference:\t\t\t"+ refs+
                        "\n ========================================\n"+
                        "Meals:\t\t"+jtxtMeals.getText()+"\n\n"+
                        "Drinks:\t\t" + jtxtDrinks.getText()+ "\n\n" +
                        "Cost of Items: \t " + jtxtCostOfItems.getText()+"\n\n"+
                         "==========================================" + "\n\n"+
                        "Tax:\t\t"+jtxtTax.getText()+"\n\n"+
                         "Subtotal:\t"+jtxtSubTotal.getText()+"\n\n"+
                          "Total:\t\t"+jtxtTotal.getText() + "\n"+
                        "=========================================="+
                        "\nDate:"+tDate.format(timer.getTime())+
                        "\tTime: "+ tTime.format(timer.getTime())+
                        "\n\n\tThank You");
    }//GEN-LAST:event_jBtnRecieptActionPerformed

    private void jtxtChickenBurgerMealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtChickenBurgerMealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtChickenBurgerMealActionPerformed

    private void jtxtFiletOFishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtFiletOFishActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtFiletOFishActionPerformed

    private void jtxtMilkShakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtMilkShakeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtMilkShakeActionPerformed

    private void jtxtVanilaMilkShakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtVanilaMilkShakeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtVanilaMilkShakeActionPerformed

    private void jBtnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTotalActionPerformed
        SubClass_child itemCost = new SubClass_child();
        
        double iSubTotal, iTax, iTotal, iMeals, iDrinks;
        itemCost.filet_o_fish = itemCost.pFilet_o_fish * Double.parseDouble(jtxtFiletOFish.getText());
        itemCost.chickenBurger = itemCost.pChickenBurger * Double.parseDouble(jtxtChickenBurger.getText());
        itemCost.chickenLegend = itemCost.pChickenLegend * Double.parseDouble(jtxtChickenLegend.getText());
        itemCost.chickenBurgerMeal = itemCost.PChickenBurgerMeal * Double.parseDouble(jtxtChickenBurgerMeal.getText());
        itemCost.baconAndCheeseBurger = itemCost.pBaconAndCheeseBurger * Double.parseDouble(jtxtBaconAndCheeseBurger.getText());

        itemCost.vanilaShake = itemCost.pVanilaShake * Double.parseDouble(jtxtMilkShake.getText());
        itemCost.vanilaCone = itemCost.pVanilaCone * Double.parseDouble(jtxtVanilaCone.getText());
        itemCost.clasicVanila = itemCost.pClasicVanila * Double.parseDouble(jtxtClasicVanila.getText());
        itemCost.vanilaMilkshake = itemCost.pVanilaMilkshake * Double.parseDouble(jtxtVanilaMilkShake.getText());
        itemCost.chocolateMilkShake = itemCost.pChocolateMilkShake * Double.parseDouble(jtxtChocotaleMilkShake.getText());

        iMeals = itemCost.getMeal();
        iDrinks = itemCost.getDrinks();
        iSubTotal = itemCost.getAmount(iMeals, iDrinks);
        iTax = itemCost.cFindTax(iSubTotal);
        iTotal = iSubTotal + iTax;
        
        String subTotal = String.format("Rs% .2f", iSubTotal);
        jtxtSubTotal.setText(subTotal);
        
        String tax = String.format("Rs% .2f", iTax);
        jtxtTax.setText(tax);
        
        String total = String.format("Rs% .2f", iTotal);
        jtxtTotal.setText(total);
        
        String meals = String.format("Rs% .2f", iMeals);
        jtxtMeals.setText(meals);
        
        String drinks = String.format("Rs% .2f", iDrinks);
        jtxtDrinks.setText(drinks);
        
        String costOfItem = String.format("Rs% .2f", iSubTotal);
        jtxtCostOfItems.setText(costOfItem);
        

     
    }//GEN-LAST:event_jBtnTotalActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        SubClass_child iExit = new SubClass_child();
        iExit.iExitSystem();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jBtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnResetActionPerformed
        JTextField clearText = null;
        // set reciept value to null
        jtxtReciept.setText(null);
        // for panel 12 
        for(Component c: jPanel2.getComponents()){
            if(c.getClass().toString().contains("javax.swing.JTextField")){
                clearText = (JTextField)c;
                clearText.setText("0");
            }
        }
        // for panel 6
        for(Component c: jPanel6.getComponents()){
            if(c.getClass().toString().contains("javax.swing.JTextField")){
                clearText = (JTextField)c;
                clearText.setText("");
            }
        }    
//        for panel 9
        for(Component c: jPanel9.getComponents()){
            if(c.getClass().toString().contains("javax.swing.JTextField")){
                clearText = (JTextField)c;
                clearText.setText("");
            }
        }    
        
        // fro panel 8 
        for(Component c: jPanel8.getComponents()){
            if(c.getClass().toString().contains("javax.swing.JTextField")){
                clearText = (JTextField)c;
                clearText.setText("0");
            }
    }//GEN-LAST:event_jBtnResetActionPerformed
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Resturent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Resturent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Resturent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Resturent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Resturent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnReciept;
    private javax.swing.JButton jBtnReset;
    private javax.swing.JButton jBtnTotal;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlblSubTotal;
    private javax.swing.JLabel jlblSubTotal1;
    private javax.swing.JLabel jlblSubTotal2;
    private javax.swing.JLabel jlblSubTotal3;
    private javax.swing.JLabel jlblSubTotal4;
    private javax.swing.JLabel jlblSubTotal5;
    private javax.swing.JLabel jlblTax;
    private javax.swing.JLabel jlblTax1;
    private javax.swing.JLabel jlblTax2;
    private javax.swing.JLabel jlblTax3;
    private javax.swing.JLabel jlblTax4;
    private javax.swing.JLabel jlblTax5;
    private javax.swing.JLabel jlblTotal;
    private javax.swing.JLabel jlblTotal1;
    private javax.swing.JLabel jlblTotal2;
    private javax.swing.JLabel jlblTotal3;
    private javax.swing.JLabel jlblTotal4;
    private javax.swing.JLabel jlblTotal5;
    private javax.swing.JTextField jtxtBaconAndCheeseBurger;
    private javax.swing.JTextField jtxtChickenBurger;
    private javax.swing.JTextField jtxtChickenBurgerMeal;
    private javax.swing.JTextField jtxtChickenLegend;
    private javax.swing.JTextField jtxtChocotaleMilkShake;
    private javax.swing.JTextField jtxtClasicVanila;
    private javax.swing.JTextField jtxtCostOfItems;
    private javax.swing.JTextField jtxtDrinks;
    private javax.swing.JTextField jtxtFiletOFish;
    private javax.swing.JTextField jtxtMeals;
    private javax.swing.JTextField jtxtMilkShake;
    private javax.swing.JTextArea jtxtReciept;
    private javax.swing.JTextField jtxtSubTotal;
    private javax.swing.JTextField jtxtTax;
    private javax.swing.JTextField jtxtTotal;
    private javax.swing.JTextField jtxtVanilaCone;
    private javax.swing.JTextField jtxtVanilaMilkShake;
    // End of variables declaration//GEN-END:variables

}